version: 2.1

# Declare and configure orbs (reusable components)
orbs:
  docker: circleci/docker@2.4.0
  heroku: circleci/heroku@2.0.0
  # snyk: snyk/snyk@2.0.2

jobs:
  build:
    docker:
      - image: python:3.13.0a2-slim
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install -r requirements.txt

      - run:
          name: Install pytest
          command: |
            python -m pip install pytest

  test:
    docker:
      - image: python:3.13.0a2-slim
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install -r requirements.txt

      - run:
          name: Install pytest
          command: |
            python -m pip install pytest

      - run:
          name: Run tests on app.py with pytest
          command: |
            python -m pytest tests/test_app.py

  # Job to scan for vulnerabilities and push Docker image to Docker Hub
  # scan:
  #   docker:
  #     - image: python:3.13.0a2-slim
  #   steps:
  #     # Set up access to the Docker daemon
  #     - setup_remote_docker
  #     - checkout
  #     # Build the Docker image
  #     - run: docker build -t $DOCKER_LOGIN/$IMAGE_NAME:latest .
  #     # Login to Docker Hub using environment variables
  #     - run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin
  #     # Push the image to Docker Hub
  #     - run: docker push $DOCKER_LOGIN/$IMAGE_NAME:latest
  #     # Run Snyk scan on the Docker image
  #     - snyk/scan:
  #         docker-image-name: $DOCKER_LOGIN/$IMAGE_NAME:latest
  #         severity-threshold: high


  build-and-push:
    docker:
      - image: python:3.13.0a2-slim
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$IMAGE_NAME
          tag: latest
      - docker/push:
          image: $DOCKER_LOGIN/$IMAGE_NAME
          tag: latest

  pull-and-deploy:
    docker:
      - image: python:3.13.0a2-slim
    steps:
      - setup_remote_docker
      - heroku/install
      - run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_LOGIN}" --password-stdin
      - run:
          name: Pull Image From Docker Hub
          command: docker pull $DOCKER_LOGIN/$IMAGE_NAME:latest
      - run:
          name: Heroku Container Push With Image From Docker Hub
          command: |
              heroku container:login
              docker tag $DOCKER_LOGIN/$IMAGE_NAME:latest registry.heroku.com/$HEROKU_APP_NAME/web
              # format --- docker tag <image name from docker hub> registry.heroku.com/<app-name>/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web
              # format --- docker push registry.heroku.com/<app-name>/web
              heroku container:release web -a $HEROKU_APP_NAME

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      # - scan:
      #     requires:
      #       - test
      - build-and-push:
          requires:
            - test
      - pull-and-deploy:
          requires:
            - build-and-push
